### PR TITLE
Add support of org.fusesource.jansi.Ansi.disable property

### PR DESCRIPTION
**Pull request by charphi**
Related to https://github.com/remkop/picocli/issues/1106

### CODE REVIEW

**Review by remkop — COMMENTED** [review]
Hi @charphi, these changes look good, thank you!

Related to our discussion in https://github.com/remkop/picocli/issues/1106,
did you have a chance to verify that the dll is not extracted when user code looks like this?

```java
    public static void main(String[] args) {
        try (AnsiConsole ansi = AnsiConsole.windowsInstall()) {
            new CommandLine(new MyApp()).execute(args);
        } 
    }
```

**Comment by charphi** [comment]
I've tested it and the dll is not extracted on my system (Windows 10 and Oracle Java 8).

**Comment by remkop** [comment]
Great, thank you! I merged the change, I will do a release as soon as I can.

**Comment by charphi** [comment]
Ok thanks

**Comment by remkop** [comment]
I finally got around to creating a release for this. Sorry for the wait!

[picocli-jansi-graalvm 1.2.0](https://github.com/remkop/picocli-jansi-graalvm/releases/tag/v1.2.0) has been released.

**Pull request merged**
